### ISSUE TITLE
Allow slurm configuration update outside of module level

### ISSUE THREAD

**Issue by NeoExtended** [d-krupke/slurminade#2]
Currently the slurm configuration must be configured at module level, as the decorator will directly create a `SimpleSlurm` object with the current config.
This behaviour can be inconvenient in cases where the slurm configuration is dynamically computed, or loaded from a separate configuration file. The `SimpleSlurm` object therefore should be created after calling `.distribute` to enable prior `slurminade.update_default_configuration()` calls to take effect.

**Comment by d-krupke** [comment]
Fixed in https://github.com/d-krupke/slurminade/commit/79434f2d76fb3a620a9db830540cba39822261d7
The slurm access point will now only be called on dispatch. This will use all default configurations set up at this point.
I am not sure, how fast creating this access point is every time. Maybe we have to add some caching.
